import React from 'react';
import { AGENT_TOOL_POLICY, AGENT_UNAVAILABLE, BEDROOM_TOOL_EXAMPLE, CUSTOM_FLOORPLAN_EXAMPLE } from './agent-workflow.ts';

export default function AgentGuide() {
  return <article className="ft-agent-guide-content">
    <h2>Connect to the planner tab</h2>
    <p>Use the same browser tab the human is viewing. The planner registers native tools on <code>document.modelContext</code>; this guide page does not. Use your runtime’s documented browser WebMCP discovery and invocation capability on the planner tab. This is not a remote MCP endpoint.</p>
    <p>Do not guess commands such as <code>webmcp_list_tools</code>. A “WebMCP · registered” badge only confirms page registration, not that your agent runtime can invoke the tools.</p>
    <p className="ft-agent-stop">{AGENT_UNAVAILABLE}</p>
    <h2>Create a new room</h2>
    <ol>
      <li>Discover the planner tab’s native tools. Confirm <code>generateRoom</code> is available and read its schema.</li>
      <li>Call <code>generateRoom</code> with dimensions in centimetres, room profile and openings, including an entrance. A 3 × 4.5 m room is <code>widthCm: 300, depthCm: 450</code>. Ask about missing measurements or clearly agree provisional assumptions with the user.</li>
      <li>The page creates a separate furnished proposal, preserves the previous room, and shows the new room type and dimensions. Inspect <code>operationSucceeded</code>, <code>validation</code>, <code>brief</code> and <code>omitted</code>; successful execution does not mean a complete or valid layout.</li>
      <li>Verify with <code>getRoomState</code>, <code>listFurniture</code> and <code>checkLayout</code>, each with <code>{'which: "proposal"'}</code>. Use the returned proposal ID and latest revision for edits. Do not change views simply to read a different snapshot.</li>
      <li>Leave the furniture in Proposal. Confirm the human-facing planner tab shows the requested room heading, dimensions and proposal before saying it is visible. Report warnings and omissions, and invite the human to review and Apply.</li>
    </ol>
    <h2>Recreate an L-shape or nook from a drawing</h2>
    <p>Interpret the user’s dimensioned drawing into an ordered <code>floorPlan.points</code> list. The origin is the bounding box’s top-left; x runs east and y runs south. Walk around the perimeter in either direction, record every corner once, and do not repeat the first point at the end. Every edge must be horizontal or vertical. The declared <code>widthCm</code> and <code>depthCm</code> must equal the point list’s bounding box.</p>
    <p>Floortris derives stable segments in list order: the first edge is <code>wall-1</code>, the next is <code>wall-2</code>, and so on. For each door, window, or wall-mounted TV on a custom outline, use the returned segment ID plus its outward <code>wall</code> direction. Segment offsets start at that segment’s normalized top/left endpoint, independent of which direction you traced the polygon. Call <code>getRoomState</code> and read <code>wallSegments</code> rather than guessing. Floortris rejects diagonals, crossed walls, missing segment IDs, furniture in cut-out areas, and routes through those areas.</p>
    <p>This example is a 5 × 5 m envelope with its lower-right 2 × 2 m corner removed. Replace every number with the drawing’s measured dimensions:</p>
    <pre><code>{JSON.stringify(CUSTOM_FLOORPLAN_EXAMPLE, null, 2)}</code></pre>
    <p><strong>{AGENT_TOOL_POLICY}</strong> Do not use “Try a proposal,” “Try again,” room forms, DOM scripts or direct storage edits as substitutes for native tools. Human editing stays available.</p>
    <h2>Keep the room visible to its owner</h2>
    <p>Rooms are saved in this browser’s local storage. A <code>?room=…</code> link selects an existing local room; it does not transfer a room to another browser, device or isolated agent session. If the user cannot see the room, verify the same browser session and active document before claiming it is open.</p>
    <h2>Edit the existing room</h2>
    <p>Read <code>getRoomState</code> first. Reuse its active layout proposal; if none exists, call <code>createProposal</code> with the accepted revisions. Use <code>proposeLayout</code>, <code>findPlacements</code> and furniture tools inside that draft. Prefer the first checked candidate: results rank functional geometry (door/TV safety, usable clearances, real furniture backs and sofa-table spacing) above decorative distribution. Verify <code>checkedRules</code>, <code>frontFacing</code>, <code>backWall</code> and <code>backGapCm</code> instead of inferring orientation from a 2D rotation value. Changes to accepted room geometry, openings or rules require a setup proposal and human confirmation.</p>
    <h2>Create one-off measured furniture</h2>
    <p>Use <code>createCustomFurniture</code> only inside an active layout proposal. Supply a human-readable label, one closed floor-furniture <code>kind</code>, exact width/depth/height and top-left position in centimetres, a quarter-turn rotation, a listed local furniture palette, and a unique idempotency key. The position is the top-left of the rotated plan envelope. The command rejects any new blocking boundary, collision, height, door, window, radiator, walking, use-zone or relationship issue rather than leaving an invalid custom object in the draft.</p>
    <p>The supported kinds are sofa, chair, table, coffee table, desk, storage, bed, rug and plant. They activate the same rules as catalogue objects. The tool does not accept tags, HTML/SVG, code, remote model URLs, arbitrary forms, rule overrides, fixed fixtures or wall/ceiling mounts. A custom chair may name an existing desk with <code>linkedDeskId</code>; the engine verifies that relationship. Custom beds do not claim a human sleep-size classification, and custom storage does not claim wardrobe, bedside or office-storage roles, so agent-authored labels cannot complete those briefs.</p>
    <p>The result repeats the measured envelope, closed provenance and <code>review.requiresHumanApply</code>. Read the object back with <code>listFurniture</code>, inspect it in 2D/3D under its CUSTOM identity, and use <code>checkLayout</code>. <code>updateFurniture</code> may move or rotate it and <code>setAppearance</code> may change its local palette, but its dimensions, kind and provenance stay fixed. Remove and recreate it to change those facts. It remains a one-off record inside this local room document; there is no remote asset library or commerce.</p>
    <h2>Add window treatments and lights</h2>
    <p>Call <code>listCatalogue</code> to get the typed fixture variants, then place them in the active layout proposal. Curtains and blinds are not free-standing furniture: pass <code>attachedOpeningId</code> for a window returned by <code>getRoomState</code>. Floortris derives their wall segment, position and measured fit. Curtains include a shallow 15 cm room-side projection checked against doors, radiators and furniture; blinds fit the glazing and reserve no floor cells.</p>
    <p>Ceiling lights use <code>kind: ceiling_light</code> and an <code>originCell</code> inside the actual ceiling outline, including an L-shaped room’s missing corners. Choose pendant, flush, track or recessed variants. The engine derives their mount height and reports a pendant below its documented 200 cm Floortris planning head-clearance assumption. That assumption is layout guidance, not an electrical, accessibility or building-code claim.</p>
    <p>Wall lights require a real <code>wallAnchor</code> and a measured <code>elevationCm</code>. For a custom room, include the <code>segmentId</code> returned in <code>wallSegments</code>; height, windows, doors and nearby tall furniture are checked. Floor lamps use ordinary floor collision and walking rules. Table lamps require <code>supportObjectId</code> naming an existing table, desk or cabinet; Floortris centres the lamp on the measured support surface and rejects overhang or a stale link.</p>
    <p>Lights may set <code>lightingZone</code> to <code>ambient</code>, <code>seating</code>, <code>reading</code> or <code>circulation</code>. The returned zone warnings are simple proximity and entrance-route guidance, not lux, glare, wiring or code analysis. Always read <code>checkLayout</code> after placement and leave the exact reviewed revision for the human to Apply.</p>
    <h2>Choose wallpaper and flooring</h2>
    <p>Call <code>listCatalogue</code> and read <code>palettes.wall</code> and <code>palettes.floor</code>. Texture entries include stable IDs, names, descriptions, tags and repeat sizes. Use those IDs in <code>generateRoom.appearance</code> or <code>setAppearance</code> with the active proposal ID and latest revision. Read back <code>getRoomState.appearance</code> to verify the selection. Finishes do not change dimensions, locks or rule flags. These are concept visuals, not real product listings or permission to decorate rented rooms. Wallpaper is visible in 3D; floor textures also appear in the 2D furniture view.</p>
    <h2>Example request, not a measured room</h2>
    <p>This example assumes a double bed, two bedside tables, storage, no workspace, no windows and an 80 cm south-wall entrance. Replace those assumptions with the user’s actual room. Discover the current schema before calling <code>generateRoom</code>; use a unique request key and keep it for retries.</p>
    <pre><code>{JSON.stringify(BEDROOM_TOOL_EXAMPLE, null, 2)}</code></pre>
  </article>;
}
