import type { AppState, Furniture, Kind, RoomProfile, Rules, Size, Wall } from './model.ts';
import type { Form } from './forms.ts';
export type Variant = { id: string; name: string; kind: Kind; sizeCm: Size; description: string; palette: string; form?: Form; backEdge?: Wall; tags?: string[]; recommendedProfiles?: RoomProfile['kind'][]; fixtureType?: Furniture['fixtureType']; lightingZone?: Furniture['lightingZone'] };
export type Finish = { id: string; name: string; color: string; description?: string; tags?: string[]; pack?: string; conceptOnly?: boolean; texture?: { url: string; repeatCm: [number, number]; kind: 'wallpaper' | 'flooring' } };
export const PALETTES: Record<'furniture' | 'wall' | 'floor', Finish[]> = {
  furniture: [{ id: 'moss', name: 'Moss', color: '#8d9c83' }, { id: 'oat', name: 'Oat', color: '#d7cdbd' }, { id: 'clay', name: 'Clay', color: '#bd856b' }, { id: 'graphite', name: 'Graphite', color: '#58615f' }, { id: 'oak', name: 'Oak', color: '#c3a782' }],
  wall: [
    { id: 'cream', name: 'Chalk', color: '#f4f1e8' }, { id: 'stone', name: 'Stone', color: '#e7e5dd' }, { id: 'warm', name: 'Warm white', color: '#f5eade' },
    { id: 'sage-botanical', name: 'Sage botanical', color: '#e5e8d9', description: 'Sage leaves on ivory paper; calm botanical wallpaper.', tags: ['botanical', 'sage', 'calm'], pack: 'studio-01', conceptOnly: true, texture: { url: '/textures/sage-botanical.webp', repeatCm: [60, 60], kind: 'wallpaper' } },
    { id: 'clay-arches', name: 'Clay arches', color: '#edd8c6', description: 'Terracotta geometric arches on cream; warm graphic wallpaper.', tags: ['geometric', 'terracotta', 'warm'], pack: 'studio-01', conceptOnly: true, texture: { url: '/textures/clay-arches.webp', repeatCm: [80, 80], kind: 'wallpaper' } },
    { id: 'blue-gingham', name: 'Blue gingham', color: '#d6e2e8', description: 'Soft blue and ivory checks; a cosy woven-paper look.', tags: ['check', 'blue', 'cosy'], pack: 'studio-01', conceptOnly: true, texture: { url: '/textures/blue-gingham.webp', repeatCm: [40, 40], kind: 'wallpaper' } },
    { id: 'woven-linen', name: 'Woven linen', color: '#ded4c4', description: 'Fine oatmeal linen weave; quiet neutral wallpaper.', tags: ['linen', 'neutral', 'minimal'], pack: 'studio-01', conceptOnly: true, texture: { url: '/textures/woven-linen.webp', repeatCm: [40, 40], kind: 'wallpaper' } },
  ],
  floor: [
    { id: 'oak', name: 'Light oak', color: '#e8dfce' }, { id: 'ash', name: 'Ash', color: '#e6e5df' }, { id: 'cork', name: 'Cork', color: '#dcc5a7' },
    { id: 'pale-oak', name: 'Pale oak planks', color: '#dfcbae', description: 'Pale matte oak with natural grain and straight planks.', tags: ['wood', 'oak', 'natural'], pack: 'studio-01', conceptOnly: true, texture: { url: '/textures/pale-oak.webp', repeatCm: [120, 120], kind: 'flooring' } },
    { id: 'warm-terrazzo', name: 'Warm terrazzo', color: '#ece1d4', description: 'Cream terrazzo with small clay, sage and charcoal chips.', tags: ['terrazzo', 'speckled', 'warm'], pack: 'studio-01', conceptOnly: true, texture: { url: '/textures/warm-terrazzo.webp', repeatCm: [80, 80], kind: 'flooring' } },
  ],
};
export const CATALOGUE: Variant[] = [
  { id: 'arc-sofa-200', name: 'Arc sofa · 200', kind: 'sofa', sizeCm: { w: 200, d: 80, h: 82 }, description: 'Three-seat sofa · the main lounge seat; pair with a wall TV via targetSofaId', palette: 'moss', recommendedProfiles: ['lounge'] } ,
  { id: 'arc-sofa-160', name: 'Arc sofa · 160', kind: 'sofa', sizeCm: { w: 160, d: 80, h: 82 }, description: 'Two-seat sofa · lounge seating for a shorter wall', palette: 'clay', recommendedProfiles: ['lounge'] } ,
  { id: 'frame-tv-120', name: 'Frame TV · 120', kind: 'tv', sizeCm: { w: 120, d: 6, h: 68 }, description: 'Wall TV · mounts on a wall, occupies no floor; link it to a sofa with targetSofaId', palette: 'graphite', recommendedProfiles: ['lounge'] } ,
  { id: 'line-desk-100', name: 'Line desk · 100', kind: 'desk', sizeCm: { w: 100, d: 60, h: 74 }, description: 'Compact desk · needs chair-pull clearance in front; link a chair with linkedDeskId', palette: 'oak', recommendedProfiles: ['lounge', 'bedroom', 'home_office'] } ,
  { id: 'line-desk-140', name: 'Line desk · 140', kind: 'desk', sizeCm: { w: 140, d: 60, h: 74 }, description: 'Desk · needs chair-pull clearance in front; link a chair with linkedDeskId', palette: 'oat', recommendedProfiles: ['lounge', 'bedroom', 'home_office'] } ,
  { id: 'line-desk-180', name: 'Line desk · 180', kind: 'desk', sizeCm: { w: 180, d: 80, h: 74 }, description: 'Wide desk · needs chair-pull clearance in front; link a chair with linkedDeskId', palette: 'graphite', recommendedProfiles: ['lounge', 'bedroom', 'home_office'] } ,
  { id: 'pebble-table-80', name: 'Pebble table · 80', kind: 'coffee_table', sizeCm: { w: 80, d: 40, h: 38 }, description: 'Small coffee table · low, so it clears a TV sightline but still blocks the floor', palette: 'oak', recommendedProfiles: ['lounge'] } ,
  { id: 'pebble-table-120', name: 'Pebble table · 120', kind: 'coffee_table', sizeCm: { w: 120, d: 60, h: 38 }, description: 'Coffee table · low enough to sit under a TV sightline', palette: 'clay', recommendedProfiles: ['lounge'] } ,
  { id: 'folio-storage-80', name: 'Folio cabinet · 80', kind: 'storage', sizeCm: { w: 80, d: 40, h: 100 }, description: 'Low cabinet · general storage; needs front clearance to open', palette: 'moss', recommendedProfiles: ['lounge', 'bedroom', 'home_office'] } ,
  { id: 'nest-chair-60', name: 'Nest chair · 60', kind: 'chair', sizeCm: { w: 60, d: 60, h: 80 }, description: 'Work chair · the default desk chair; link with linkedDeskId to satisfy a workspace brief', palette: 'clay', recommendedProfiles: ['lounge', 'bedroom', 'home_office'] } ,
  { id: 'weave-rug-200', name: 'Weave rug · 200', kind: 'rug', sizeCm: { w: 200, d: 160, h: 1 }, description: 'Large rug · a floor finish; never blocks a route or a clearance', palette: 'oat', recommendedProfiles: ['lounge', 'bedroom', 'home_office', 'bathroom_concept'] } ,
  { id: 'fern-40', name: 'Fern · 40', kind: 'plant', sizeCm: { w: 40, d: 40, h: 110 }, description: 'Floor plant · small footprint for an awkward corner', palette: 'moss', recommendedProfiles: ['lounge', 'bedroom', 'home_office', 'bathroom_concept'] } ,
  { id: 'weave-mat-80', name: 'Weave mat · 80', kind: 'rug', sizeCm: { w: 80, d: 60, h: 1 }, description: 'Bath mat · a floor finish; never blocks a route', palette: 'oat', recommendedProfiles: ['bathroom_concept', 'bedroom'] },
  { id: 'haven-single-100', name: 'Haven single bed · 100', kind: 'bed', sizeCm: { w: 100, d: 200, h: 95 }, description: 'Single bed · satisfies a single sleeping brief; wants access along a long side', palette: 'oat', tags: ['bed', 'single'], recommendedProfiles: ['bedroom'] },
  { id: 'haven-double-140', name: 'Haven double bed · 140', kind: 'bed', sizeCm: { w: 140, d: 200, h: 100 }, description: 'Double bed · satisfies a double sleeping brief; wants access along both long sides', palette: 'clay', tags: ['bed', 'double'], recommendedProfiles: ['bedroom'] },
  { id: 'haven-king-160', name: 'Haven king bed · 160', kind: 'bed', sizeCm: { w: 160, d: 220, h: 105 }, description: 'King bed · satisfies a king sleeping brief; needs the most side access of any bed', palette: 'moss', tags: ['bed', 'king'], recommendedProfiles: ['bedroom'] },
  { id: 'nook-bedside-40', name: 'Nook bedside table · 40', kind: 'storage', sizeCm: { w: 40, d: 40, h: 52 }, description: 'Bedside table · place at the bed head; counts toward the bedside brief', palette: 'oak', form: 'bedside', tags: ['bedside'], recommendedProfiles: ['bedroom'] },
  { id: 'tallline-wardrobe-100', name: 'Tallline wardrobe · 100', kind: 'storage', sizeCm: { w: 100, d: 60, h: 210 }, description: 'Wardrobe · satisfies the bedroom storage brief; full height, needs door clearance', palette: 'oat', form: 'wardrobe', tags: ['wardrobe', 'clothes-storage', 'wall-backed'], recommendedProfiles: ['bedroom'] },
  { id: 'tallline-wardrobe-160', name: 'Tallline wardrobe · 160', kind: 'storage', sizeCm: { w: 160, d: 60, h: 210 }, description: 'Wide wardrobe · satisfies the bedroom storage brief; needs door clearance', palette: 'moss', form: 'wardrobe', tags: ['wardrobe', 'clothes-storage', 'wall-backed'], recommendedProfiles: ['bedroom'] },
  { id: 'fold-bench-100', name: 'Fold bench · 100', kind: 'table', sizeCm: { w: 100, d: 40, h: 45 }, description: 'Bench · low seating, or a landing spot at the foot of a bed', palette: 'oak', form: 'bench', tags: ['bedroom'], recommendedProfiles: ['bedroom'] },
  { id: 'archive-tall-80', name: 'Archive tall cabinet · 80', kind: 'storage', sizeCm: { w: 80, d: 45, h: 180 }, description: 'Tall office storage · satisfies the office storage brief; needs front clearance', palette: 'graphite', tags: ['office-storage'], recommendedProfiles: ['home_office'] },
  { id: 'arc-sofa-140', name: 'Arc sofa · 140', kind: 'sofa', sizeCm: { w: 140, d: 80, h: 82 }, description: 'Loveseat · two seats for a small lounge or a reading corner', palette: 'moss', form: 'loveseat', tags: ['seating'], recommendedProfiles: ['lounge'] },
  { id: 'arc-corner-240', name: 'Arc corner sofa · 240', kind: 'sofa', sizeCm: { w: 240, d: 160, h: 82 }, description: 'Corner sofa · L-shaped, but checked as its full rectangle, so it needs a real corner', palette: 'clay', form: 'corner', tags: ['seating', 'corner'], recommendedProfiles: ['lounge'] },
  { id: 'nest-armchair-80', name: 'Nest armchair · 80', kind: 'chair', sizeCm: { w: 80, d: 80, h: 82 }, description: 'Armchair · a single lounge seat; not a work chair, so it will not satisfy a desk link', palette: 'clay', form: 'armchair', tags: ['seating'], recommendedProfiles: ['lounge'] },
  { id: 'pebble-side-45', name: 'Pebble side table · 45', kind: 'table', sizeCm: { w: 45, d: 45, h: 50 }, description: 'Side table · sits beside a sofa or an armchair', palette: 'oak', form: 'side', recommendedProfiles: ['lounge'] },
  { id: 'pebble-ottoman-60', name: 'Pebble ottoman · 60', kind: 'coffee_table', sizeCm: { w: 60, d: 60, h: 42 }, description: 'Ottoman · low footstool; clears a TV sightline', palette: 'oat', form: 'ottoman', recommendedProfiles: ['lounge'] },
  { id: 'folio-media-140', name: 'Folio media unit · 140', kind: 'storage', sizeCm: { w: 140, d: 40, h: 55 }, description: 'Media unit · low and wide, designed to sit under a wall TV', palette: 'graphite', form: 'media', tags: ['wall-backed'], recommendedProfiles: ['lounge'] },
  { id: 'folio-shelf-80', name: 'Folio shelf · 80', kind: 'storage', sizeCm: { w: 80, d: 32, h: 180 }, description: 'Bookshelf · tall open shelving; back it to a wall and leave front clearance', palette: 'oat', form: 'shelving', tags: ['wall-backed'], recommendedProfiles: ['lounge'] },
  { id: 'fold-console-120', name: 'Fold console · 120', kind: 'table', sizeCm: { w: 120, d: 35, h: 75 }, description: 'Console table · narrow, sits flush to a wall or behind a sofa', palette: 'oak', form: 'console', recommendedProfiles: ['lounge'] },
  { id: 'frame-tv-140', name: 'Frame TV · 140', kind: 'tv', sizeCm: { w: 140, d: 6, h: 80 }, description: 'Wall TV · larger panel; link to a sofa with targetSofaId', palette: 'graphite', recommendedProfiles: ['lounge'] },
  { id: 'frame-tv-165', name: 'Frame TV · 165', kind: 'tv', sizeCm: { w: 165, d: 7, h: 94 }, description: 'Wall TV · largest panel; wants a long uninterrupted wall', palette: 'graphite', recommendedProfiles: ['lounge'] },
  { id: 'weave-rug-160', name: 'Weave rug · 160', kind: 'rug', sizeCm: { w: 160, d: 120, h: 1 }, description: 'Rug · a floor finish; never blocks a route', palette: 'clay', recommendedProfiles: ['lounge', 'bedroom', 'home_office', 'bathroom_concept'] },
  { id: 'weave-rug-240', name: 'Weave rug · 240', kind: 'rug', sizeCm: { w: 240, d: 170, h: 1 }, description: 'Extra-large rug · a floor finish that anchors a whole seating group', palette: 'moss', recommendedProfiles: ['lounge', 'bedroom', 'home_office', 'bathroom_concept'] },
  { id: 'fern-70', name: 'Fern · 70', kind: 'plant', sizeCm: { w: 70, d: 70, h: 160 }, description: 'Large floor plant · taller and wider than the small fern', palette: 'moss', recommendedProfiles: ['lounge', 'bedroom', 'home_office', 'bathroom_concept'] },
  { id: 'haven-day-90', name: 'Haven day bed · 90', kind: 'bed', sizeCm: { w: 90, d: 190, h: 85 }, description: 'Day bed · satisfies a single sleeping brief; its back runs along a long side, so wall it', palette: 'graphite', form: 'day', backEdge: 'west', tags: ['bed', 'single', 'wall-backed'], recommendedProfiles: ['bedroom'] },
  { id: 'nook-bedside-45', name: 'Nook bedside table · 45', kind: 'storage', sizeCm: { w: 45, d: 40, h: 58 }, description: 'Bedside table · a little wider; counts toward the bedside brief', palette: 'oak', form: 'bedside', tags: ['bedside'], recommendedProfiles: ['bedroom'] },
  { id: 'nook-bedside-35', name: 'Nook bedside table · 35', kind: 'storage', sizeCm: { w: 35, d: 35, h: 48 }, description: 'Compact bedside table · for a tight gap beside a bed', palette: 'clay', form: 'bedside', tags: ['bedside'], recommendedProfiles: ['bedroom'] },
  { id: 'tallline-wardrobe-120', name: 'Tallline wardrobe · 120', kind: 'storage', sizeCm: { w: 120, d: 60, h: 210 }, description: 'Wardrobe · satisfies the bedroom storage brief; needs door clearance', palette: 'graphite', form: 'wardrobe', tags: ['wardrobe', 'clothes-storage', 'wall-backed'], recommendedProfiles: ['bedroom'] },
  { id: 'folio-drawers-90', name: 'Folio drawers · 90', kind: 'storage', sizeCm: { w: 90, d: 45, h: 85 }, description: 'Chest of drawers · counts as clothes storage for the bedroom brief; needs front clearance', palette: 'oak', form: 'drawers', tags: ['clothes-storage'], recommendedProfiles: ['bedroom'] },
  { id: 'fold-blanket-100', name: 'Fold blanket box · 100', kind: 'storage', sizeCm: { w: 100, d: 45, h: 50 }, description: 'Blanket box · low storage at the foot of a bed; this version checks a front access zone', palette: 'oat', form: 'chest', tags: ['bedroom'], recommendedProfiles: ['bedroom'] },
  { id: 'line-dressing-110', name: 'Line dressing table · 110', kind: 'desk', sizeCm: { w: 110, d: 45, h: 75 }, description: 'Dressing table · counts as the bedroom workspace desk; link a chair with linkedDeskId', palette: 'oak', form: 'dressing', tags: ['dressing'], recommendedProfiles: ['bedroom'] },
  { id: 'nest-bedroom-55', name: 'Nest bedroom chair · 55', kind: 'chair', sizeCm: { w: 55, d: 55, h: 80 }, description: 'Bedroom chair · occasional seating, not a work chair', palette: 'moss', form: 'armchair', tags: ['seating'], recommendedProfiles: ['bedroom'] },
  { id: 'line-desk-80', name: 'Line desk · 80', kind: 'desk', sizeCm: { w: 80, d: 60, h: 74 }, description: 'Compact desk · smallest work surface; needs chair-pull clearance and a linked chair', palette: 'oak', recommendedProfiles: ['home_office'] },
  { id: 'line-corner-160', name: 'Line corner desk · 160', kind: 'desk', sizeCm: { w: 160, d: 160, h: 74 }, description: 'Corner desk · L-shaped, but checked as its full square, so it needs a real corner', palette: 'oat', form: 'corner', tags: ['corner-desk'], recommendedProfiles: ['home_office'] },
  { id: 'line-standing-140', name: 'Line standing desk · 140', kind: 'desk', sizeCm: { w: 140, d: 70, h: 110 }, description: 'Standing desk · taller worktop; still needs chair-pull clearance if a chair is linked', palette: 'graphite', form: 'standing', tags: ['standing'], recommendedProfiles: ['home_office'] },
  { id: 'nest-task-62', name: 'Nest task chair · 62', kind: 'chair', sizeCm: { w: 62, d: 62, h: 95 }, description: 'Task chair · the default office desk chair; link with linkedDeskId', palette: 'graphite', form: 'task', tags: ['work-seating'], recommendedProfiles: ['home_office'] },
  { id: 'nest-guest-52', name: 'Nest guest chair · 52', kind: 'chair', sizeCm: { w: 52, d: 52, h: 82 }, description: 'Guest chair · leave it unlinked to satisfy the office guest-seating brief', palette: 'clay', form: 'dining', tags: ['seating'], recommendedProfiles: ['home_office'] },
  { id: 'archive-low-120', name: 'Archive low cabinet · 120', kind: 'storage', sizeCm: { w: 120, d: 45, h: 75 }, description: 'Low office storage · counts toward the office storage brief; needs front clearance', palette: 'graphite', form: 'drawers', tags: ['office-storage'], recommendedProfiles: ['home_office'] },
  { id: 'archive-pedestal-42', name: 'Archive pedestal · 42', kind: 'storage', sizeCm: { w: 42, d: 55, h: 60 }, description: 'Under-desk pedestal · small office storage that tucks beside a desk', palette: 'moss', form: 'drawers', tags: ['office-storage'], recommendedProfiles: ['home_office'] },
  { id: 'folio-bookcase-100', name: 'Folio bookcase · 100', kind: 'storage', sizeCm: { w: 100, d: 35, h: 200 }, description: 'Office bookcase · tall open shelving; counts toward the office storage brief', palette: 'graphite', form: 'shelving', tags: ['office-storage', 'wall-backed'], recommendedProfiles: ['home_office'] },
  { id: 'fold-meeting-120', name: 'Fold meeting table · 120', kind: 'table', sizeCm: { w: 120, d: 80, h: 74 }, description: 'Meeting table · wants clear floor on every side for chairs', palette: 'oak', form: 'meeting', tags: ['meeting', 'all-side-clearance'], recommendedProfiles: ['home_office'] },
  { id: 'folio-vanity-80', name: 'Folio vanity · 80', kind: 'storage', sizeCm: { w: 80, d: 45, h: 85 }, description: 'Vanity unit · under-basin storage; back it to a wall', palette: 'moss', form: 'vanity', tags: ['bathroom-storage', 'wall-backed'], recommendedProfiles: ['bathroom_concept'] },
  { id: 'folio-laundry-45', name: 'Folio laundry cabinet · 45', kind: 'storage', sizeCm: { w: 45, d: 45, h: 60 }, description: 'Laundry basket · small open storage that fits a corner', palette: 'oat', form: 'basket', tags: ['bathroom-storage'], recommendedProfiles: ['bathroom_concept'] },
  { id: 'folio-bathshelf-60', name: 'Folio bathroom shelf · 60', kind: 'storage', sizeCm: { w: 60, d: 25, h: 170 }, description: 'Tall bathroom shelving · narrow footprint against a wall', palette: 'clay', form: 'shelving', tags: ['bathroom-storage', 'wall-backed'], recommendedProfiles: ['bathroom_concept'] },
  { id: 'nest-stool-38', name: 'Nest stool · 38', kind: 'chair', sizeCm: { w: 38, d: 38, h: 45 }, description: 'Stool · a small backless seat', palette: 'oak', form: 'stool', tags: ['seating'], recommendedProfiles: ['bathroom_concept'] },
  { id: 'weave-mat-60', name: 'Weave mat · 60', kind: 'rug', sizeCm: { w: 60, d: 45, h: 1 }, description: 'Small bath mat · a floor finish; never blocks a route', palette: 'oat', recommendedProfiles: ['bathroom_concept', 'bedroom'] },
  { id: 'soft-curtains-160', name: 'Soft curtains · made to window', kind: 'window_treatment', sizeCm: { w: 160, d: 15, h: 210 }, description: 'Made-to-window curtains · attachedOpeningId is required; width, drop and shallow projection are measured against that window.', palette: 'oat', fixtureType: 'curtains', tags: ['window-treatment', 'wall-attached'], recommendedProfiles: ['lounge', 'bedroom', 'home_office'] },
  { id: 'line-blind-160', name: 'Line blind · made to window', kind: 'window_treatment', sizeCm: { w: 160, d: 2, h: 120 }, description: 'Made-to-window blind · attachedOpeningId is required; it exactly fits the opening and has no floor occupancy.', palette: 'oat', fixtureType: 'blind', tags: ['window-treatment', 'wall-attached', 'no-floor-occupancy'], recommendedProfiles: ['lounge', 'bedroom', 'home_office'] },
  { id: 'halo-pendant-45', name: 'Halo pendant', kind: 'ceiling_light', sizeCm: { w: 45, d: 45, h: 55 }, description: 'Ceiling pendant · its plan envelope must stay inside the real ceiling outline; bottom height is checked as a planning head-clearance assumption.', palette: 'clay', fixtureType: 'pendant', lightingZone: 'seating', tags: ['lighting', 'ceiling-mounted', 'seating-light'], recommendedProfiles: ['lounge', 'bedroom', 'home_office'] },
  { id: 'halo-flush-35', name: 'Halo flush light', kind: 'ceiling_light', sizeCm: { w: 35, d: 35, h: 12 }, description: 'Compact flush ceiling light · supplies an ambient zone without occupying floor space.', palette: 'oat', fixtureType: 'flush', lightingZone: 'ambient', tags: ['lighting', 'ceiling-mounted', 'ambient-light'], recommendedProfiles: ['lounge', 'bedroom', 'home_office'] },
  { id: 'line-track-120', name: 'Line track · 120', kind: 'ceiling_light', sizeCm: { w: 120, d: 12, h: 18 }, description: 'Directional track light · its complete measured track stays inside the custom ceiling polygon.', palette: 'graphite', fixtureType: 'track', lightingZone: 'circulation', tags: ['lighting', 'ceiling-mounted', 'circulation-light'], recommendedProfiles: ['lounge', 'home_office'] },
  { id: 'dot-recessed-12', name: 'Dot recessed light', kind: 'ceiling_light', sizeCm: { w: 12, d: 12, h: 3 }, description: 'Recessed light marker · a ceiling-plan fixture, not an electrical or installation specification.', palette: 'oat', fixtureType: 'recessed', lightingZone: 'ambient', tags: ['lighting', 'ceiling-mounted', 'ambient-light'], recommendedProfiles: ['lounge', 'bedroom', 'home_office'] },
  { id: 'arc-wall-light-24', name: 'Arc wall light', kind: 'wall_light', sizeCm: { w: 24, d: 12, h: 32 }, description: 'Wall sconce · requires an explicit wall segment and mounting elevation; doors, windows and tall furniture are checked.', palette: 'clay', fixtureType: 'wall_sconce', lightingZone: 'ambient', tags: ['lighting', 'wall-attached', 'ambient-light'], recommendedProfiles: ['lounge', 'bedroom', 'home_office'] },
  { id: 'stem-floor-lamp-45', name: 'Stem floor lamp', kind: 'floor_lamp', sizeCm: { w: 45, d: 45, h: 165 }, description: 'Floor lamp · uses normal solid footprint, collision and walking rules; suited to a reading seat.', palette: 'oak', fixtureType: 'floor_lamp', lightingZone: 'reading', tags: ['lighting', 'reading-light'], recommendedProfiles: ['lounge', 'bedroom', 'home_office'] },
  { id: 'nook-table-lamp-28', name: 'Nook table lamp', kind: 'table_lamp', sizeCm: { w: 28, d: 28, h: 48 }, description: 'Table lamp · supportObjectId must name a table, desk or cabinet whose top contains it.', palette: 'oat', fixtureType: 'table_lamp', lightingZone: 'reading', tags: ['lighting', 'supported-object', 'reading-light'], recommendedProfiles: ['lounge', 'bedroom', 'home_office'] },
];
/** Visual treatment for a placed piece. Owned and measured pieces have no
 *  variantId and therefore no form, so they keep the kind's own shape. */
export const formFor = (variantId?: string): Form | undefined => variantId ? CATALOGUE.find(v => v.id === variantId)?.form : undefined;
export function fromVariant(variantId: string, id: string): Furniture {
  const v = CATALOGUE.find(v => v.id === variantId);
  if (!v) throw new Error('variant_unavailable');
  return { id, label: v.name, kind: v.kind, ownership: 'catalogue', variantId, sizeCm: { ...v.sizeCm }, originCell: { x: 0, y: 0 }, rotation: 0, ...(v.backEdge ? { backEdge: v.backEdge } : {}), elevationCm: v.kind === 'tv' ? 110 : 0, ...(v.kind === 'tv' ? { wallAnchor: { wall: 'north' as const, offsetCm: 180 } } : {}), ...(v.fixtureType ? { fixtureType: v.fixtureType } : {}), ...(v.lightingZone ? { lightingZone: v.lightingZone } : {}), locked: {}, appearance: v.palette, requiredInRoom: false, tags: [...(v.tags || (v.kind === 'sofa' ? ['seating'] : v.kind === 'chair' ? ['work-seating'] : []))] };
}
export const DEFAULT_RULES: Rules = { cellCm: 20, H_lowCm: 70, walkHardCm: 60, walkPreferredCm: 80, storageFrontCm: 60, chairPullCm: 60, bedLongSideAccessCm: 40, radiatorFrontCm: 20, windowFrontCm: 20, ceilingCm: 240, requiredKinds: ['sofa', 'tv'], deskNearWindow: true, openFloorM2: 2 };
export function makeDemo(): AppState {
  const sofa: Furniture = { id: 'owned-sofa', label: 'Your sofa', kind: 'sofa', ownership: 'owned', sizeCm: { w: 220, d: 90, h: 85 }, originCell: { x: 9, y: 18 }, rotation: 180, elevationCm: 0, locked: { position: true, rotation: true, size: true }, appearance: 'moss', requiredInRoom: true, tags: ['seating'] };
  const radiator: Furniture = { id: 'radiator-east', label: 'Radiator', kind: 'radiator', ownership: 'fixed', sizeCm: { w: 20, d: 100, h: 60 }, originCell: { x: 29, y: 14 }, wallAnchor: { wall: 'east', offsetCm: 280 }, rotation: 90, elevationCm: 0, locked: { position: true, size: true, rotation: true }, appearance: 'oat', requiredInRoom: true, tags: [] };
  // Fixed radiator dimensions describe its floor projection directly, without a rotated catalogue convention.
  radiator.rotation = 0;
  return { version: 2, currentRevision: 1, ruleRevision: 1, sequence: 0, proposal: null, rules: structuredClone(DEFAULT_RULES), room: { name: 'The everyday lounge', widthCm: 600, depthCm: 480, profile: { kind: 'lounge' }, openings: [
    { id: 'entrance', kind: 'door', wall: 'south', offsetCm: 20, widthCm: 100, hinge: 'start', swing: 'in', angle: 90, mechanism: 'hinged', entrance: true },
    { id: 'window-west', kind: 'window', wall: 'west', offsetCm: 80, widthCm: 180, sillCm: 95, headCm: 215, type: 'fixed', windowAccess: false },
  ], fixtures: [radiator] }, inventory: [structuredClone(sofa)], current: { furniture: [sofa], appearance: { wall: 'cream', floor: 'oak' } } };
}
