'use client';
import Link from 'next/link';
import { useState } from 'react';
import { BUNDLED_EVAL_REPORT, runLocalEvaluation, type EvalReport } from './evaluation.ts';

export default function EvalDashboard(){
  const[report,setReport]=useState<EvalReport>(BUNDLED_EVAL_REPORT),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const run=async()=>{setBusy(true);setError('');try{setReport(await runLocalEvaluation());}catch(value){setError(value instanceof Error?value.message:String(value));}finally{setBusy(false);}};
  const summary=report.summary;
  return <main className="eval-page"><header><Link href="/">← Floortris</Link><span>Local evidence</span></header><section className="eval-hero"><p>AGENT EVALUATION</p><h1>Repeatable rooms, visible outcomes.</h1><p>This suite runs the seven difficult gallery briefs twice, using the same local planner and rule engine as the workspace. It makes no network request and never clicks Apply.</p><button onClick={()=>void run()} disabled={busy}>{busy?'Running 14 local plans…':'Run evaluation locally'}</button>{error&&<p role="alert">{error}</p>}</section><section className="eval-metrics"><article><strong>{summary.briefCompletionRate}%</strong><span>brief completion</span></article><article><strong>{summary.hardViolations}</strong><span>final hard violations</span></article><article><strong>{summary.humanOnlyApplyRate}%</strong><span>Current preserved</span></article><article><strong>{summary.repeatValidityRate}%</strong><span>repeat validity</span></article><article><strong>{summary.toolCalls}</strong><span>tool calls</span></article><article><strong>{summary.rejections}</strong><span>rejections</span></article></section><section className="eval-table"><h2>{report.cases.length?'Latest local run':'Bundled snapshot pending first local run'}</h2>{report.cases.length?<table><thead><tr><th>Brief</th><th>Brief met</th><th>Hard</th><th>Calls</th><th>Time</th><th>Apply guard</th><th>Repeat</th></tr></thead><tbody>{report.cases.map(item=><tr key={item.id}><td>{item.id.replace('benchmark-','').replaceAll('-',' ')}</td><td>{item.briefComplete?'✓':'—'}</td><td>{item.hardViolations}</td><td>{item.toolCalls}</td><td>{item.elapsedMs} ms</td><td>{item.humanOnlyApply?'✓':'×'}</td><td>{item.repeatValid?'✓':'×'}</td></tr>)}</tbody></table>:<p>Choose Run evaluation locally to create current evidence on this device.</p>}<p>Metrics are product regression evidence, not proof of real-world feasibility, safety or accessibility compliance.</p></section></main>;
}
