import React, { useEffect, useMemo, useRef, useState, useSyncExternalStore } from 'react';
import { CATALOGUE, PALETTES, makeDemo } from './data.ts';
import { bounds, validate, wallBand } from './engine.ts';
import { clone, faces, type AppState, type Candidate, type CommandResult, type Furniture, type Layout, type Opening, type Report, type Room, type Rules, type WindowOpening, type Wall, type Rotation } from './model.ts';
import { createStore, proposalStatus, type FloortrisStore } from './store.ts';
import { registerFloortrisTools, type WebMCPState } from './webmcp.ts';
import './floortris.css';

type View = 'current' | 'proposal' | 'compare';
type Layer = 'clearances' | 'walking' | 'tv';
const STORAGE_KEY = 'floortris.v1.local';
const uid = () => typeof crypto !== 'undefined' && 'randomUUID' in crypto ? crypto.randomUUID() : `human-${Date.now()}-${Math.random()}`;
const fmt = (n: number) => Number.isInteger(n) ? String(n) : n.toFixed(1);
const nice = (s: string) => s.replaceAll('_', ' ').replace('kind:', '');
const palette = (id: string) => PALETTES.furniture.find(p => p.id === id)?.color || '#c9c5b9';
function loadState(): AppState {
  try { const raw = localStorage.getItem(STORAGE_KEY); if (raw) { const state = JSON.parse(raw) as AppState; if (state.version === 1 && state.current?.furniture && state.inventory && state.room.widthCm >= 240 && state.room.widthCm <= 1000 && state.room.depthCm >= 240 && state.room.depthCm <= 1000 && state.rules.cellCm === 20) { validate(state.current, state.room, state.rules, state.inventory); return state; } } } catch { /* The human can always recover the demo; malformed local data is never sent remotely. */ }
  return makeDemo();
}
function Icon({ name }: { name: 'plus' | 'lock' | 'arrow' | 'check' | 'rotate' | 'close' | 'grid' | 'spark' }) {
  return <span className={`ft-icon ft-icon-${name}`} aria-hidden="true">{{ plus: '+', lock: '▣', arrow: '↗', check: '✓', rotate: '↻', close: '×', grid: '▦', spark: '✦' }[name]}</span>;
}
function Brand() { return <div className="ft-brand"><span className="ft-brandmark"><i /><i /><i /><i /><i /></span><span>floortris<span className="ft-brand-dot">.</span></span></div>; }
function Shape({ item, small = false }: { item: Furniture | { kind: string; appearance?: string; rotation?: number }; small?: boolean }) {
  return <div className={`ft-shape ft-shape-${item.kind} ft-face-${faces[(item.rotation || 0) as Rotation]} ${small ? 'ft-shape-small' : ''}`} style={{ '--piece-color': palette(item.appearance || 'oak') } as React.CSSProperties}>
    {item.kind === 'sofa' && <><i className="ft-sofa-back" /><i className="ft-sofa-arm ft-arm-a" /><i className="ft-sofa-arm ft-arm-b" /><div className="ft-cushions"><i /><i /><i /></div></>}
    {item.kind === 'desk' && <><i className="ft-desk-book" /><i className="ft-desk-pad" /><i className="ft-desk-cup" /></>}
    {item.kind === 'coffee_table' && <><i className="ft-table-book" /><i className="ft-table-bowl" /></>}
    {item.kind === 'chair' && <><i className="ft-chair-back" /><i className="ft-chair-seat" /></>}
    {item.kind === 'storage' && <><i /><i /></>}
    {item.kind === 'plant' && <><i /><i /><i /></>}
    {item.kind === 'bed' && <><i /><i /></>}
  </div>;
}
function Board({ layout, room, rules, report, title, revision, compact, selected, onSelect, onMove, layers, issueFocus, editable }: { layout: Layout; room: Room; rules: Rules; report: Report; title: string; revision: number; compact?: boolean; selected: string | null; onSelect: (id: string) => void; onMove: (id: string, origin: { x: number; y: number }) => void; layers: Layer[]; issueFocus: string[]; editable: boolean }) {
  const board = useRef<HTMLDivElement>(null), drag = useRef<{ id: string; startX: number; startY: number; x: number; y: number; cellPx: number } | null>(null);
  const [ghost, setGhost] = useState<{ id: string; x: number; y: number } | null>(null);
  const position = (r: { x: number; y: number; w: number; d: number }) => ({ left: `${r.x / room.widthCm * 100}%`, top: `${r.y / room.depthCm * 100}%`, width: `${r.w / room.widthCm * 100}%`, height: `${r.d / room.depthCm * 100}%` });
  const down = (event: React.PointerEvent<HTMLButtonElement>, item: Furniture) => {
    onSelect(item.id); if (!editable || item.locked.position || item.kind === 'tv' || !board.current) return;
    event.currentTarget.setPointerCapture(event.pointerId);
    drag.current = { id: item.id, startX: event.clientX, startY: event.clientY, x: item.originCell.x, y: item.originCell.y, cellPx: board.current.clientWidth * 20 / room.widthCm };
  };
  const move = (event: React.PointerEvent<HTMLButtonElement>) => { const d = drag.current; if (!d) return; setGhost({ id: d.id, x: d.x + Math.round((event.clientX - d.startX) / d.cellPx), y: d.y + Math.round((event.clientY - d.startY) / d.cellPx) }); };
  const up = () => { const d = drag.current; if (d && ghost && (d.x !== ghost.x || d.y !== ghost.y)) onMove(d.id, { x: ghost.x, y: ghost.y }); drag.current = null; setGhost(null); };
  return <section className={`ft-board-shell ${compact ? 'ft-compact' : ''}`}>
    <div className="ft-board-caption"><span><i className={`ft-snapshot-dot ${title === 'Proposal' ? 'proposal' : ''}`} />{title} <em>rev. {revision}</em></span><span>{(room.widthCm * room.depthCm / 10000).toFixed(1)} m²</span></div>
    <div className="ft-ruler-top"><span /><span>{fmt(room.widthCm / 100)} m</span><span /></div>
    <div className="ft-board-wrap"><div className="ft-ruler-side">{fmt(room.depthCm / 100)} m</div>
      <div ref={board} className="ft-board" style={{ aspectRatio: `${room.widthCm}/${room.depthCm}`, '--grid-x': `${20 / room.widthCm * 100}%`, '--grid-y': `${20 / room.depthCm * 100}%`, '--floor': PALETTES.floor.find(p => p.id === layout.appearance.floor)?.color, '--wall': PALETTES.wall.find(p => p.id === layout.appearance.wall)?.color } as React.CSSProperties}>
        <div className="ft-board-grid" />
        {layout.furniture.filter(o => o.kind === 'rug').map(o => <button key={o.id} className={`ft-furniture ft-rug ${selected === o.id ? 'selected' : ''}`} style={position(bounds(o))} onPointerDown={e => down(e, o)} onPointerMove={move} onPointerUp={up} aria-label={`${o.label}, ${o.sizeCm.w} by ${o.sizeCm.d} centimetres`}><Shape item={o} /></button>)}
        {report.cells.map(c => {
          let type = '';
          if (layers.includes('walking')) type = c.flags.includes('walk_clear') ? 'walk-clear' : c.flags.includes('walk_tight') ? 'walk-tight' : '';
          if (layers.includes('tv')) type = c.flags.includes('tv_blocked') || c.flags.includes('tv_unknown') ? 'tv-block' : c.flags.includes('tv_seat') ? 'tv-seat' : c.flags.includes('tv_clear') ? 'tv-clear' : type;
          if (layers.includes('clearances')) type = c.flags.includes('door_leaf_blocked') ? 'door-leaf' : c.flags.includes('door_swing_reserved') ? 'door-sweep' : c.flags.includes('radiator_keepout') ? 'radiator-zone' : c.flags.includes('window_envelope') ? 'window-zone' : c.flags.includes('path_unreachable') ? 'path-block' : c.flags.includes('path_reachable') ? 'path-target' : type;
          return type ? <span key={`${c.x},${c.y}`} className={`ft-cell ft-cell-${type}`} style={position({ x: c.x * 20, y: c.y * 20, w: 20, d: 20 })} /> : null;
        })}
        {room.openings.map(o => {
          const wall = o.wall, horizontal = wall === 'north' || wall === 'south';
          const style: React.CSSProperties = horizontal ? { left: `${o.offsetCm / room.widthCm * 100}%`, width: `${o.widthCm / room.widthCm * 100}%`, [wall === 'north' ? 'top' : 'bottom']: '-3px' } : { top: `${o.offsetCm / room.depthCm * 100}%`, height: `${o.widthCm / room.depthCm * 100}%`, [wall === 'west' ? 'left' : 'right']: '-3px' };
          return <div key={o.id} className={`ft-opening ft-opening-${o.kind} ft-wall-${wall}`} style={style}><span>{o.kind === 'window' ? 'WINDOW' : o.entrance ? 'ENTRANCE' : 'DOOR'}</span></div>;
        })}
        {room.fixtures.map(o => <div key={o.id} className={`ft-fixed ft-fixed-${o.kind}`} style={position(bounds(o))}><span>{o.kind === 'radiator' ? 'RADIATOR' : o.label}</span></div>)}
        {layout.furniture.filter(o => o.kind !== 'rug' && o.kind !== 'tv').map(o => {
          const shown = ghost?.id === o.id ? { ...o, originCell: { x: ghost.x, y: ghost.y } } : o;
          return <button key={o.id} className={`ft-furniture ${selected === o.id ? 'selected' : ''} ${issueFocus.includes(o.id) ? 'ft-conflict' : ''} ${o.locked.position ? 'ft-locked' : ''}`} style={position(bounds(shown))} onPointerDown={e => down(e, o)} onPointerMove={move} onPointerUp={up} onPointerCancel={() => { drag.current = null; setGhost(null); }} onKeyDown={e => { const delta = { ArrowLeft: [-1, 0], ArrowRight: [1, 0], ArrowUp: [0, -1], ArrowDown: [0, 1] }[e.key]; if (delta && editable) { e.preventDefault(); onMove(o.id, { x: o.originCell.x + delta[0], y: o.originCell.y + delta[1] }); } }} aria-label={`${o.label}, ${o.sizeCm.w} by ${o.sizeCm.d} centimetres${o.locked.position ? ', position locked' : ', drag or use arrow keys to move'}`}>
            <Shape item={o} /><span className="ft-item-label">{o.kind === 'sofa' && o.ownership === 'owned' ? 'YOUR SOFA' : o.kind === 'coffee_table' ? 'TABLE' : nice(o.kind).toUpperCase()}{o.locked.position && <span className="ft-piece-lock"> ▣</span>}</span><span className="ft-item-dim">{o.sizeCm.w} × {o.sizeCm.d} cm</span>
          </button>;
        })}
        {layout.furniture.filter(o => o.kind === 'tv' && o.wallAnchor).map(o => {
          const anchor = o.wallAnchor!;
          return <button key={o.id} onClick={() => onSelect(o.id)} className={`ft-wall-tv ft-wall-${anchor.wall} ${selected === o.id ? 'selected' : ''}`} style={position(wallBand(room, anchor.wall, anchor.offsetCm, o.sizeCm.w, 12))} aria-label={`${o.label}, wall mounted, no floor footprint`}><span>WALL TV · {o.sizeCm.w} CM</span></button>;
        })}
        {layers.includes('clearances') && report.zones.filter(z => z.id.startsWith('sofa:')).map(z => <div key={z.id} className="ft-zone-label" style={{ left: `${(z.rect.x + z.rect.w / 2) / room.widthCm * 100}%`, top: `${(z.rect.y + z.rect.d / 2) / room.depthCm * 100}%` }}>{z.reachable ? '↗' : '!'} SOFA APPROACH · {rules.walkHardCm} CM</div>)}
        <span className="ft-north">N ↑</span>
      </div>
    </div>
    <div className="ft-board-foot"><span>Each square is 20 × 20 cm</span><span>{editable ? 'Drag to place · arrow keys to nudge' : 'Aligned comparison · select a view to edit'}</span></div>
  </section>;
}
function NumberField({ label, value, onChange, min = 0, max = 1000, step = 20 }: { label: string; value: number; onChange: (v: number) => void; min?: number; max?: number; step?: number }) { return <label className="ft-field"><span>{label}</span><div><input type="number" value={value} min={min} max={max} step={step} onChange={e => { const n = Number(e.target.value); if (Number.isFinite(n)) onChange(n); }} /><span>cm</span></div></label>; }
function SetupPanel({ state, store, onResult, close }: { state: AppState; store: FloortrisStore; onResult: (r: CommandResult) => void; close: () => void }) {
  const [room, setRoom] = useState(() => clone(state.proposal?.kind === 'setup' ? state.proposal.room : state.room));
  const [rules, setRules] = useState(() => clone(state.proposal?.kind === 'setup' ? state.proposal.rules : state.rules));
  const [saving, setSaving] = useState(false);
  const updateOpening = (id: string, patch: Partial<Opening>) => setRoom({ ...room, openings: room.openings.map(o => o.id === id ? { ...o, ...patch } as Opening : o) });
  const stage = async () => {
    setSaving(true);
    try {
      if (state.proposal && state.proposal.kind !== 'setup') { onResult({ operationSucceeded: false, error: { code: 'active_proposal_exists', message: 'Discard or apply the active layout draft before staging room inputs.' } }); return; }
      if (!store.getState().proposal) { const s = store.getState(), result = await store.execute('createProposal', { kind: 'setup', expectedCurrentRevision: s.currentRevision, expectedRuleRevision: s.ruleRevision, idempotencyKey: uid() }); if (!result.operationSucceeded) { onResult(result); return; } }
      const run = async (name: string, args: Record<string, unknown>) => { const p = store.getState().proposal!; const r = await store.execute(name, { proposalId: p.id, revision: p.revision, ...args }); if (!r.operationSucceeded) throw r; };
      await run('setRoomGeometry', { widthCm: room.widthCm, depthCm: room.depthCm, name: room.name });
      const constraints = Object.fromEntries(Object.entries(rules).filter(([key]) => key !== 'cellCm')); await run('setConstraints', { constraints });
      for (const opening of room.openings) await run('setOpening', { opening });
      onResult({ operationSucceeded: true, message: 'Room inputs staged. Review the changes and confirm below.' });
    } catch (r) { onResult(r as CommandResult); } finally { setSaving(false); }
  };
  const p = state.proposal?.kind === 'setup' ? state.proposal : null;
  return <div className="ft-modal-backdrop" onClick={close}><section className="ft-modal ft-setup" role="dialog" aria-modal="true" aria-labelledby="setup-title" onClick={e => e.stopPropagation()}><div className="ft-modal-head"><div><p className="ft-eyebrow">THE PHYSICAL ROOM</p><h2 id="setup-title">Room inputs & assumptions</h2></div><button className="ft-icon-button" onClick={close} aria-label="Close room inputs">×</button></div>
    <p className="ft-muted">These are demo measurements until you replace them. Changes are staged before your explicit confirmation; the planner cannot change accepted dimensions.</p>
    <div className="ft-form-grid"><NumberField label="Room width" value={room.widthCm} min={240} onChange={widthCm => setRoom({ ...room, widthCm })} /><NumberField label="Room depth" value={room.depthCm} min={240} onChange={depthCm => setRoom({ ...room, depthCm })} /><NumberField label="Ceiling" value={rules.ceilingCm} min={100} max={500} onChange={ceilingCm => setRules({ ...rules, ceilingCm })} /><NumberField label="Low-object cutoff" value={rules.H_lowCm} max={300} step={10} onChange={H_lowCm => setRules({ ...rules, H_lowCm })} /><NumberField label="Hard walking width" value={rules.walkHardCm} min={20} max={200} onChange={walkHardCm => setRules({ ...rules, walkHardCm })} /><NumberField label="Preferred width" value={rules.walkPreferredCm} min={20} max={200} onChange={walkPreferredCm => setRules({ ...rules, walkPreferredCm })} /></div>
    <div className="ft-setup-openings">{room.openings.map(o => <div key={o.id} className="ft-opening-form"><h3>{o.kind === 'door' ? 'Entrance / door' : 'Window'} <span>{o.id}</span></h3><div className="ft-form-grid"><label className="ft-field"><span>Wall</span><select value={o.wall} onChange={e => updateOpening(o.id, { wall: e.target.value as Opening['wall'] })}>{['north', 'east', 'south', 'west'].map(w => <option key={w}>{w}</option>)}</select></label><NumberField label="Offset from wall start" value={o.offsetCm} onChange={offsetCm => updateOpening(o.id, { offsetCm })} /><NumberField label="Opening width" value={o.widthCm} min={20} max={400} onChange={widthCm => updateOpening(o.id, { widthCm })} />{o.kind === 'door' ? <><label className="ft-field"><span>Hinge</span><select value={o.hinge} onChange={e => updateOpening(o.id, { hinge: e.target.value as 'start' | 'end' })}><option value="start">Start of opening</option><option value="end">End of opening</option></select></label><label className="ft-field"><span>Swing · tested at 90°</span><select value={o.swing} onChange={e => updateOpening(o.id, { swing: e.target.value as 'in' | 'out' })}><option value="in">Inward</option><option value="out">Outward</option></select></label><label className="ft-check"><input type="checkbox" checked={o.entrance} onChange={e => updateOpening(o.id, { entrance: e.target.checked })} />Entrance</label></> : <><NumberField label="Sill height" value={o.sillCm} step={5} max={500} onChange={sillCm => updateOpening(o.id, { sillCm })} /><NumberField label="Head height" value={o.headCm} step={5} max={500} onChange={headCm => updateOpening(o.id, { headCm })} /><label className="ft-field"><span>Opening mechanism</span><select value={o.type} onChange={e => updateOpening(o.id, { type: e.target.value as WindowOpening['type'] })}>{['fixed', 'side_hinge', 'sash', 'unknown'].map(type => <option key={type}>{type}</option>)}</select></label><label className="ft-check"><input type="checkbox" checked={o.windowAccess} onChange={e => updateOpening(o.id, { windowAccess: e.target.checked })} />Require access to this window</label></>}</div></div>)}</div>
    <div className="ft-inline-buttons"><button className="ft-button ft-secondary" onClick={() => setRoom({ ...room, openings: [...room.openings, { id: `window-${room.openings.length + 1}`, kind: 'window', wall: 'north', offsetCm: 20, widthCm: 100, sillCm: 95, headCm: 210, type: 'unknown', windowAccess: false }] })}>+ Window</button><button className="ft-button ft-secondary" onClick={() => setRoom({ ...room, openings: [...room.openings, { id: `door-${room.openings.length + 1}`, kind: 'door', wall: 'east', offsetCm: 40, widthCm: 100, hinge: 'start', swing: 'in', angle: 90, mechanism: 'hinged', entrance: false }] })}>+ Door</button></div>
    <h3>Required lounge functions</h3><div className="ft-inline-checks">{(['sofa', 'tv', 'desk', 'storage'] as const).map(kind => <label key={kind} className="ft-check"><input type="checkbox" checked={rules.requiredKinds.includes(kind)} onChange={e => setRules({ ...rules, requiredKinds: e.target.checked ? [...rules.requiredKinds, kind] : rules.requiredKinds.filter(k => k !== kind) })} />{kind === 'tv' ? 'Wall TV' : nice(kind)}</label>)}</div>
    <p className="ft-small-note">20 cm grid. Storage-front rectangle: {rules.storageFrontCm} cm. Desk pull zone: {rules.chairPullCm} cm plus a free approach at its outer edge. Radiator-front assumption: {rules.radiatorFrontCm} cm. Fixed radiator remains at its measured demo position. No certification, light analysis or equipment safety assessment.</p>
    {p && <div className="ft-setup-review"><h3>Review staged revision {p.revision}</h3><ul><li>Room: {state.room.widthCm} × {state.room.depthCm} → <strong>{p.room.widthCm} × {p.room.depthCm} cm</strong></li><li>Walking: {state.rules.walkHardCm}/{state.rules.walkPreferredCm} → <strong>{p.rules.walkHardCm}/{p.rules.walkPreferredCm} cm</strong></li><li>Low cutoff / ceiling: {state.rules.H_lowCm}/{state.rules.ceilingCm} → <strong>{p.rules.H_lowCm}/{p.rules.ceilingCm} cm</strong></li><li>Required: <strong>{p.rules.requiredKinds.join(', ') || 'none'}</strong></li></ul><details><summary>All staged measurements and openings</summary><pre>{JSON.stringify({ room: p.room, rules: p.rules }, null, 2)}</pre></details><p>Confirming changes accepted inputs, and may reveal conflicts in the existing arrangement.</p><button className="ft-button ft-primary" onClick={() => { const result = store.confirmSetup(p.id, p.revision); onResult(result); if (result.operationSucceeded) close(); }}>Confirm room inputs · revision {p.revision}</button></div>}
    <div className="ft-modal-actions"><button className="ft-button ft-secondary" onClick={close}>Close</button><button className="ft-button ft-primary" onClick={stage} disabled={saving}>{saving ? 'Staging…' : p ? 'Update staged inputs' : 'Stage these inputs'} <Icon name="arrow" /></button></div>
  </section></div>;
}

function FloortrisWorkspace({ store: suppliedStore }: { store?: FloortrisStore }) {
  const [store] = useState(() => suppliedStore || createStore(typeof window === 'undefined' ? makeDemo() : loadState()));
  const [state, setState] = useState(store.getState()), [view, setView] = useState<View>('current'), [selected, setSelected] = useState<string | null>('owned-sofa');
  const [layers, setLayers] = useState<Layer[]>(['clearances']), [libraryKind, setLibraryKind] = useState('all'), [showSetup, setShowSetup] = useState(false), [showOwned, setShowOwned] = useState(false), [showTools, setShowTools] = useState(false);
  const [notice, setNotice] = useState<{ text: string; error: boolean } | null>(null), [busy, setBusy] = useState(false), [suggestions, setSuggestions] = useState<Candidate[]>([]), [focus, setFocus] = useState<string[]>([]), [review, setReview] = useState<{ id: string; revision: number } | null>(null), [webmcp, setWebmcp] = useState<WebMCPState>({ state: 'checking', count: 0, message: 'Checking native document tools…' });
  const [ownedForm, setOwnedForm] = useState({ label: 'My armchair', kind: 'chair', w: 80, d: 80, h: 85 });
  const abort = useRef<AbortController | null>(null);
  useEffect(() => store.subscribe(() => { setState(store.getState()); setSuggestions([]); }), [store]);
  useEffect(() => { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); } catch { queueMicrotask(() => setNotice({ text: 'Local saving is unavailable. Keep this tab open or export your room.', error: true })); } }, [state]);
  useEffect(() => registerFloortrisTools(store, setWebmcp), [store]);
  useEffect(() => () => abort.current?.abort(), []);
  const { current: currentLayout, room: currentRoom, rules: currentRules, inventory: currentInventory } = state;
  const currentReport = useMemo(() => validate(currentLayout, currentRoom, currentRules, currentInventory), [currentLayout, currentRoom, currentRules, currentInventory]);
  const proposalReport = useMemo(() => state.proposal ? validate(state.proposal.layout, state.proposal.room, state.proposal.rules, state.inventory) : null, [state]);
  const which = view === 'proposal' && state.proposal ? 'proposal' : 'current';
  const layout = which === 'proposal' ? state.proposal!.layout : state.current, rules = which === 'proposal' ? state.proposal!.rules : state.rules, report = which === 'proposal' ? proposalReport! : currentReport;
  const item = layout.furniture.find(o => o.id === selected), status = proposalStatus(state), active = state.proposal;
  const onResult = (r: CommandResult) => { if (!r.operationSucceeded) setNotice({ text: r.error?.message || 'That edit could not be committed.', error: true }); else if (r.message) setNotice({ text: String(r.message), error: false }); };
  const update = (patch: Parameters<FloortrisStore['humanUpdate']>[2]) => { if (item) onResult(store.humanUpdate(which, item.id, patch)); };
  const add = (variantId: string) => { const r = store.humanAdd(which, variantId); onResult(r); if (r.operationSucceeded) { setSelected(r.objectId as string); setNotice({ text: 'Added to this layout. Check its position and live rules.', error: false }); } };
  const plan = async () => {
    setBusy(true); abort.current = new AbortController();
    try {
      if (!store.getState().proposal) { const s = store.getState(); const r = await store.execute('createProposal', { kind: 'layout', expectedCurrentRevision: s.currentRevision, expectedRuleRevision: s.ruleRevision, idempotencyKey: uid() }); if (!r.operationSucceeded) { onResult(r); return; } }
      const p = store.getState().proposal!;
      const r = await store.execute('proposeLayout', { proposalId: p.id, revision: p.revision }, abort.current.signal); onResult(r);
      if (r.operationSucceeded) setNotice({ text: r.status === 'ready_for_review' ? 'The local planner has a checked proposal. Open Proposal whenever you’re ready.' : 'The local planner committed a partial proposal. Inspect its issues and missing items.', error: false });
    } finally { setBusy(false); abort.current = null; }
  };
  const newDraft = async () => { const s = store.getState(); onResult(await store.execute('createProposal', { kind: 'layout', expectedCurrentRevision: s.currentRevision, expectedRuleRevision: s.ruleRevision, idempotencyKey: uid() })); };
  const find = async () => { if (!active || !item) return; setBusy(true); abort.current = new AbortController(); const result = await store.execute('findPlacements', { proposalId: active.id, revision: active.revision, objectId: item.id, limit: 4 }, abort.current.signal); onResult(result); setSuggestions((result.candidates as Candidate[]) || []); if (result.operationSucceeded && !(result.candidates as Candidate[])?.length) setNotice({ text: String(result.explanation), error: false }); setBusy(false); abort.current = null; };
  const exportRoom = () => { const blob = new Blob([JSON.stringify(state, null, 2)], { type: 'application/json' }), url = URL.createObjectURL(blob), link = document.createElement('a'); link.href = url; link.download = 'floortris-room.json'; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); };
  const baselineDone = rules.requiredKinds.filter(kind => layout.furniture.some(o => o.kind === kind)).length;
  return <div className="ft-app">
    <header className="ft-header"><Brand /><div className="ft-header-context"><span className="ft-context-line" />A little room to think.</div><div className="ft-header-actions"><span className="ft-local-dot" />Saved on this device<button className="ft-text-button" onClick={exportRoom}>Export room <Icon name="arrow" /></button><button className="ft-avatar" aria-label="Your local room">Y</button></div></header>
    <div className="ft-project-bar"><div><p className="ft-eyebrow">ROOM 01 <span> / </span> LOUNGE + WORK</p><h1>{state.room.name}</h1></div><div className="ft-project-actions"><span className="ft-demo-label">DEMO MEASUREMENTS</span><button className="ft-button ft-secondary" onClick={() => setShowSetup(true)}><Icon name="grid" /> Room setup</button></div></div>
    <main className="ft-workspace">
      <aside className="ft-library"><div className="ft-section-heading"><h2>Make room for you.</h2><span>01</span></div><p className="ft-muted">Start with what you own.<br />Find the pieces that fit around it.</p>
        <div className="ft-brief-card"><div><span className="ft-mini-label">YOUR ROOM BRIEF</span><span>{baselineDone}/{rules.requiredKinds.length}</span></div><p>{rules.requiredKinds.includes('desk') ? 'A lounge with room to work.' : 'A comfortable place to unwind.'}</p><div className="ft-brief-tags">{rules.requiredKinds.map(kind => <span key={kind} className={layout.furniture.some(o => o.kind === kind) ? 'done' : ''}>{layout.furniture.some(o => o.kind === kind) ? '✓' : '+'} {kind === 'tv' ? 'Wall TV' : nice(kind)}</span>)}</div><small>All required owned pieces stay in the room.</small></div>
        <div className="ft-library-label"><span>YOUR FURNITURE</span><button onClick={() => setShowOwned(!showOwned)} aria-label="Add measured owned piece">+</button></div>
        {state.inventory.map(o => <button key={o.id} className={`ft-owned-card ${selected === o.id ? 'active' : ''}`} onClick={() => { setSelected(o.id); if (!layout.furniture.some(f => f.id === o.id)) setView('current'); }}><div className="ft-owned-thumb"><Shape item={o} small /></div><span><strong>{o.label}</strong><small>{o.sizeCm.w} × {o.sizeCm.d} cm · measured</small></span><Icon name="lock" /></button>)}
        {showOwned && <form className="ft-owned-form" onSubmit={e => { e.preventDefault(); const r = store.humanAddOwned({ label: ownedForm.label, kind: ownedForm.kind as Furniture['kind'], sizeCm: { w: ownedForm.w, d: ownedForm.d, h: ownedForm.h } }); onResult(r); if (r.operationSucceeded) { setSelected(r.objectId as string); setView('current'); setShowOwned(false); } }}><label className="ft-field"><span>Piece name</span><input value={ownedForm.label} maxLength={80} required onChange={e => setOwnedForm({ ...ownedForm, label: e.target.value })} /></label><label className="ft-field"><span>Type</span><select value={ownedForm.kind} onChange={e => setOwnedForm({ ...ownedForm, kind: e.target.value })}>{['sofa', 'chair', 'desk', 'coffee_table', 'storage', 'plant', 'bed', 'rug'].map(k => <option key={k} value={k}>{nice(k)}</option>)}</select></label><div className="ft-measure-row">{(['w', 'd', 'h'] as const).map(k => <label key={k}>{k.toUpperCase()} cm<input type="number" min={1} max={600} value={ownedForm[k]} onChange={e => setOwnedForm({ ...ownedForm, [k]: Number(e.target.value) })} /></label>)}</div><p>Added to Yours as required. Dimensions stay immutable to tools.</p><button className="ft-button ft-primary" type="submit">Add measured piece</button></form>}
        <div className="ft-library-label"><span>THE SMALL CATALOGUE</span><span>{CATALOGUE.length}</span></div><div className="ft-library-filters">{[['all', 'All'], ['desk', 'Work'], ['coffee_table', 'Living'], ['rug', 'Details']].map(([kind, label]) => <button key={kind} className={libraryKind === kind ? 'active' : ''} onClick={() => setLibraryKind(kind)}>{label}</button>)}</div>
        <div className="ft-catalogue">{CATALOGUE.filter(v => libraryKind === 'all' || libraryKind === 'coffee_table' && ['sofa', 'coffee_table', 'tv', 'storage', 'chair'].includes(v.kind) || libraryKind === 'rug' && ['rug', 'plant'].includes(v.kind) || v.kind === libraryKind).map(v => <button key={v.id} className="ft-catalogue-card" onClick={() => add(v.id)} title={v.description}><div className={`ft-catalogue-thumb ft-thumb-${v.kind}`}><Shape item={{ kind: v.kind, appearance: v.palette }} small /><span>+</span></div><strong>{v.name}</strong><small>{v.sizeCm.w} × {v.sizeCm.d}{v.kind === 'tv' ? ' · wall' : ' cm'}</small></button>)}</div>
        <p className="ft-catalogue-disclaimer">Named demo variants. No real SKUs, purchasing or price claims.</p>
      </aside>
      <section className="ft-canvas-panel"><div className="ft-canvas-toolbar"><div className="ft-view-tabs" aria-label="Layout view">{(['current', 'proposal', 'compare'] as View[]).map(v => <button key={v} className={view === v ? 'active' : ''} onClick={() => { setView(v); setFocus([]); }} disabled={v !== 'current' && !active}>{v === 'current' ? 'Yours' : v === 'proposal' ? 'Proposal' : 'Compare'}{v === 'proposal' && active && <i className={status === 'ready_for_review' ? 'ready' : ''} />}</button>)}</div><span className="ft-live-check"><i />Live rule check</span></div>
        {active && <div className={`ft-proposal-strip ft-status-${status}`}><div><strong>{status === 'ready_for_review' ? 'Proposal ready for review' : status === 'stale' ? 'Proposal is stale' : status === 'blocked' ? 'Proposal needs a little work' : active.kind === 'setup' ? 'Room inputs awaiting confirmation' : 'Proposal is taking shape'}</strong><span>{status === 'stale' ? 'Yours or accepted room inputs changed. Discard and start a fresh draft.' : `Revision ${active.revision} · ${active.kind === 'setup' ? 'physical inputs staged separately' : 'your current room is unchanged'}`}</span></div><button className="ft-text-button" onClick={() => active.kind === 'setup' ? setShowSetup(true) : setView(view === 'proposal' ? 'compare' : 'proposal')}>{active.kind === 'setup' ? 'Review inputs' : view === 'proposal' ? 'Compare' : 'Inspect'} <Icon name="arrow" /></button></div>}
        <div className={`ft-boards ${view === 'compare' ? 'ft-comparison' : ''}`}>
          {(view === 'current' || view === 'compare' || !active) && <Board layout={state.current} room={state.room} rules={state.rules} report={currentReport} title="Yours" revision={state.currentRevision} compact={view === 'compare'} selected={view === 'compare' ? null : selected} onSelect={setSelected} onMove={(id, originCell) => onResult(store.humanUpdate('current', id, { originCell }))} layers={layers} issueFocus={focus} editable={view !== 'compare'} />}
          {(view === 'proposal' || view === 'compare') && active && proposalReport && <Board layout={active.layout} room={active.room} rules={active.rules} report={proposalReport} title="Proposal" revision={active.revision} compact={view === 'compare'} selected={view === 'compare' ? null : selected} onSelect={setSelected} onMove={(id, originCell) => onResult(store.humanUpdate('proposal', id, { originCell }))} layers={layers} issueFocus={focus} editable={view !== 'compare' && active.kind === 'layout'} />}
        </div>
        <div className="ft-overlay-bar"><span>SHOW ON BOARD</span>{(['clearances', 'walking', 'tv'] as Layer[]).map(layer => <button key={layer} className={layers.includes(layer) ? 'active' : ''} onClick={() => setLayers(layers.includes(layer) ? layers.filter(l => l !== layer) : [...layers, layer])}><span className={`ft-layer-symbol ft-layer-${layer}`} />{layer === 'tv' ? 'TV strip' : layer === 'walking' ? 'Walking width' : 'Use zones'}</button>)}<button className="ft-help-button" onClick={() => setShowTools(true)} aria-label="Explain board rules">?</button></div>
        <div className="ft-board-legend"><span><i className="ft-legend-clear" />{layers.includes('tv') ? 'Clear under height rule' : layers.includes('walking') ? 'Preferred width fits' : 'Reachable activity zone'}</span><span><i className="ft-legend-tight" />{layers.includes('walking') ? 'Hard minimum only' : 'Keep clear'}</span><span><i className="ft-legend-block" />Needs attention</span></div>
        <div className="ft-bottom-card"><div className="ft-bottom-graphic"><Icon name="spark" /></div><div><h3>Another way to arrange things.</h3><p>A bounded local planner can try a desk, TV and table around your owned furniture.</p><small>Deterministic page code. No chatbot or remote agent backend.</small></div>{busy ? <button className="ft-button ft-secondary" onClick={() => abort.current?.abort()}>Cancel search</button> : <button className="ft-button ft-primary" onClick={plan} disabled={active?.kind === 'setup' || status === 'stale'}>{active ? 'Improve proposal' : 'Try a proposal'} <Icon name="arrow" /></button>}</div>
      </section>
      <aside className="ft-inspector"><div className="ft-section-heading"><h2>{item ? 'The selected piece' : 'Your room, at a glance'}</h2><span>02</span></div>
        {item ? <><div className="ft-selected-preview"><Shape item={item} /><span>{item.ownership === 'owned' ? 'ALREADY YOURS' : 'CATALOGUE VARIANT'}</span></div><div className="ft-item-title"><h3>{item.label}</h3><p>{item.sizeCm.w} × {item.sizeCm.d} × {item.sizeCm.h === null ? '?' : item.sizeCm.h} cm <span>W × D × H</span></p></div>
          {item.ownership === 'owned' && <div className="ft-lock-note"><Icon name="lock" /><span><strong>Measured. Never resized by a tool.</strong>{item.locked.position ? 'Position and rotation are protected.' : 'Position is editable. Required by default.'}</span></div>}
          {which === 'current' && <label className="ft-switch-row"><span>Lock position & rotation</span><input type="checkbox" checked={!!item.locked.position && !!item.locked.rotation} onChange={e => onResult(store.humanSetLocks(item.id, { ...item.locked, position: e.target.checked, rotation: e.target.checked, ...(item.ownership === 'owned' && !e.target.checked ? {size:false} : {}) }))} /></label>}
          {item.kind === 'tv' ? <div className="ft-form-grid"><label className="ft-field"><span>Wall</span><select value={item.wallAnchor?.wall || 'north'} onChange={e => update({ wallAnchor: { wall: e.target.value as Wall, offsetCm: item.wallAnchor?.offsetCm || 0 } })}>{['north', 'east', 'south', 'west'].map(w => <option key={w}>{w}</option>)}</select></label><NumberField label="Wall offset" value={item.wallAnchor?.offsetCm || 0} onChange={offsetCm => update({ wallAnchor: { wall: item.wallAnchor?.wall || 'north', offsetCm } })} /><NumberField label="Mount bottom" value={item.elevationCm} max={500} step={10} onChange={elevationCm => update({ elevationCm })} /><label className="ft-field ft-span-two"><span>Target sofa</span><select value={item.targetSofaId || ''} onChange={e => update({ targetSofaId: e.target.value })}><option value="">Choose sofa</option>{layout.furniture.filter(o => o.kind === 'sofa').map(o => <option key={o.id} value={o.id}>{o.label}</option>)}</select></label></div> : <div className="ft-position-controls"><div className="ft-form-grid"><NumberField label="Position X" value={item.originCell.x * 20} min={-1000} onChange={x => update({ originCell: { ...item.originCell, x: Math.round(x / 20) } })} /><NumberField label="Position Y" value={item.originCell.y * 20} min={-1000} onChange={y => update({ originCell: { ...item.originCell, y: Math.round(y / 20) } })} /></div><button className="ft-button ft-secondary ft-full" onClick={() => update({ rotation: ((item.rotation + 90) % 360) as Rotation })} disabled={item.locked.rotation}><Icon name="rotate" />Rotate 90° <span>{faces[item.rotation]}</span></button></div>}
          {item.kind === 'chair' && <label className="ft-field"><span>Desk association (optional)</span><select value={item.linkedDeskId || ''} onChange={e => e.target.value && update({ linkedDeskId: e.target.value })}><option value="">Not a desk chair</option>{layout.furniture.filter(o => o.kind === 'desk').map(o => <option key={o.id} value={o.id}>{o.label}</option>)}</select></label>}
          {item.ownership === 'catalogue' && <label className="ft-field"><span>Named size variant</span><select value={item.variantId} onChange={e => update({ variantId: e.target.value })}>{CATALOGUE.filter(v => v.kind === item.kind).map(v => <option key={v.id} value={v.id}>{v.name}</option>)}</select></label>}
          <div className="ft-palette-section"><span className="ft-mini-label">FINISH · APPEARANCE ONLY</span><div className="ft-swatches">{PALETTES.furniture.map(p => <button key={p.id} className={item.appearance === p.id ? 'active' : ''} style={{ background: p.color }} title={p.name} aria-label={`Set ${p.name} finish`} onClick={() => update({ appearance: p.id })}>{item.appearance === p.id ? '✓' : ''}</button>)}</div></div>
          {which === 'current' && item.ownership === 'owned' && <details className="ft-owned-details"><summary>Your measured dimensions & requirement</summary><div className="ft-form-grid">{(['w', 'd', 'h'] as const).map(k => <NumberField key={k} label={k === 'w' ? 'Width' : k === 'd' ? 'Depth' : 'Height'} value={item.sizeCm[k] || 0} min={1} max={600} step={1} onChange={n => onResult(store.humanMeasureOwned(item.id, { ...item.sizeCm, [k]: n }))} />)}</div><label className="ft-check"><input type="checkbox" checked={item.requiredInRoom} onChange={e => onResult(store.humanSetRequired(item.id, e.target.checked))} />This owned piece must stay</label>{!item.requiredInRoom && Object.values(item.locked).some(Boolean) && <button className="ft-text-button" onClick={() => onResult(store.humanSetLocks(item.id, {}))}>Unlock all placement / removal locks</button>}<p>Changing a measurement or requirement makes an existing proposal stale. To remove this piece, make it optional and turn off position & rotation locks; measured dimensions remain protected from tools.</p></details>}
          <div className="ft-item-actions">{which === 'proposal' && active?.kind === 'layout' && <button className="ft-button ft-secondary" disabled={busy || status === 'stale'} onClick={find}>Find checked placements <Icon name="arrow" /></button>}<button className="ft-text-button ft-remove" onClick={() => onResult(store.humanRemove(which, item.id))}>Remove piece</button></div>
          {suggestions.length > 0 && <div className="ft-candidates"><span className="ft-mini-label">CHECKED AT REV. {active?.revision}</span>{suggestions.map((c, i) => <button key={c.candidateId} onClick={async () => { const p = store.getState().proposal!; onResult(await store.execute('updateFurniture', { proposalId: p.id, revision: p.revision, objectId: item.id, candidateId: c.candidateId })); }}><strong>Option {i + 1} · {c.rotation}°</strong><span>{c.wallAnchor ? `${c.wallAnchor.wall} · ${c.wallAnchor.offsetCm} cm` : `X ${c.originCell.x * 20} · Y ${c.originCell.y * 20} cm`}</span><small>Placement valid · layout {c.layoutStatus}</small></button>)}</div>}
        </> : <p className="ft-muted">Select any piece on the board to move it, choose its finish, or inspect a measured size.</p>}
        <div className="ft-rule-summary"><div className="ft-library-label"><span>THE ROOM CHECK</span><span className={report.validation.hardFailures ? 'ft-fail-count' : 'ft-pass-count'}>{report.validation.hardFailures ? `${report.validation.hardFailures} to fix` : '✓ Clear'}</span></div><div className="ft-check-row"><span>Floor route</span><strong>{report.zones.every(z => z.reachable) ? 'Connected' : 'Needs a path'}</strong></div><div className="ft-check-row"><span>Walking assumption</span><strong>{rules.walkHardCm} / {rules.walkPreferredCm} cm</strong></div><div className="ft-check-row"><span>Open rectangle</span><strong>{report.openFloorM2.toFixed(1)} m²</strong></div><div className="ft-check-row"><span>Required brief</span><strong>{report.brief.status === 'satisfied' ? 'Complete' : 'Incomplete'}</strong></div>
          {report.brief.missingRequired.map(id => <div key={id} className="ft-issue ft-issue-info"><span>+</span><p>Add {nice(id)} to complete your room brief.</p></div>)}
          {report.issues.map((issue, i) => <button key={`${issue.code}-${i}`} className={`ft-issue ft-issue-${issue.severity}`} onClick={() => { setFocus(issue.objectIds); const id = issue.objectIds.find(id => layout.furniture.some(o => o.id === id)); if (id) setSelected(id); }}><span>{issue.severity === 'block' ? '!' : '·'}</span><div><strong>{nice(issue.code)}</strong><p>{issue.message}</p></div></button>)}
          {active?.omitted.map((o, i) => <div className="ft-issue ft-issue-warning" key={i}><span>−</span><p>{o.variantId || o.objectId}: {o.reason}</p></div>)}
          {!report.validation.hardFailures && report.brief.status === 'satisfied' && <p className="ft-passed-note">The required brief and hard rules pass. TV strip clear under the selected height rule; this does not establish real-world visibility.</p>}
        </div>
        <div className="ft-native-card"><button onClick={() => setShowTools(!showTools)}><i className={webmcp.state === 'registered' ? 'connected' : ''} /><span>WebMCP <strong>{webmcp.state === 'registered' ? `${webmcp.count} native tools` : webmcp.state === 'checking' ? 'Checking…' : 'Not connected'}</strong></span><span>↗</span></button><p>{webmcp.state === 'registered' ? 'A compatible agent can edit a proposal. Only you can apply it.' : 'Native API unavailable here. The human editor and local planner are fully usable.'}</p></div>
      </aside>
    </main>
    <footer className="ft-footer"><span>FLOORTRIS V1 <i /> One room. Two possibilities.</span><div>{active ? <><button className="ft-text-button" onClick={() => { if (window.confirm('Discard this proposal? Yours will stay unchanged.')) { store.discardProposal(); setView('current'); setReview(null); } }}>Discard draft</button>{active.kind === 'layout' && <button className="ft-button ft-primary" disabled={status !== 'ready_for_review'} onClick={() => setReview({ id: active.id, revision: active.revision })}>Review & apply <Icon name="arrow" /></button>}</> : <button className="ft-text-button" onClick={newDraft}>Start an empty working draft <Icon name="plus" /></button>}<button className="ft-text-button" onClick={() => { if (window.confirm('Reset this locally saved room to the demo? Your current work will be replaced. Export first if you want a copy.')) { store.resetDemo(); setSelected('owned-sofa'); setView('current'); } }}>Reset demo</button></div></footer>
    {notice && <div className={`ft-toast ${notice.error ? 'ft-toast-error' : ''}`} role={notice.error ? 'alert' : 'status'}><span>{notice.error ? '!' : '✓'}</span><p>{notice.text}</p><button onClick={() => setNotice(null)} aria-label="Dismiss notice">×</button></div>}
    {showSetup && <SetupPanel state={state} store={store} onResult={onResult} close={() => setShowSetup(false)} />}
    {review && <div className="ft-modal-backdrop"><section className="ft-modal ft-review-modal" role="dialog" aria-modal="true" aria-labelledby="review-title"><p className="ft-eyebrow">THE FINAL MOVE IS YOURS</p><h2 id="review-title">Make this arrangement yours?</h2><p>You are reviewing proposal <strong>{review.id}, revision {review.revision}</strong>. Apply checks that exact revision, the accepted room inputs, the complete brief and every hard rule again.</p><p className="ft-small-note">Yours will be replaced with this proposal. If the draft changes while this review is open, Apply refuses the stale revision.</p><div className="ft-modal-actions"><button className="ft-button ft-secondary" onClick={() => { setReview(null); setView('compare'); }}>Compare first</button><button className="ft-button ft-primary" onClick={() => { const r = store.applyProposal(review.id, review.revision); onResult(r); if (r.operationSucceeded) { setView('current'); setReview(null); setNotice({ text: 'Applied. This arrangement is now Yours.', error: false }); } }}>Apply revision {review.revision}</button></div><button className="ft-text-button" onClick={() => setReview(null)}>Cancel</button></section></div>}
    {showTools && <div className="ft-modal-backdrop" onClick={() => setShowTools(false)}><section className="ft-modal" role="dialog" aria-modal="true" aria-labelledby="tools-title" onClick={e => e.stopPropagation()}><div className="ft-modal-head"><div><p className="ft-eyebrow">TRANSPARENT BY DESIGN</p><h2 id="tools-title">One board. One set of rules.</h2></div><button className="ft-icon-button" onClick={() => setShowTools(false)} aria-label="Close tools information">×</button></div><h3>Native WebMCP status</h3><p>{webmcp.message}</p><p>There is no external agent service in this app. A browser that exposes the native API can discover these 14 document tools. A registration badge is not proof of agent discovery or successful execution.</p><div className="ft-tool-list">{['getRoomState', 'listFurniture', 'listCatalogue', 'setRoomGeometry', 'setOpening', 'setConstraints', 'createProposal', 'placeFurniture', 'updateFurniture', 'removeFurniture', 'proposeLayout', 'findPlacements', 'setAppearance', 'checkLayout'].map(t => <code key={t}>{t}</code>)}</div><h3>What the board checks</h3><p>20 cm conservative grid occupancy. Orthogonal square footprints connect the open entrance to real activity zones. A 60 cm hard minimum and 80 cm preference are product assumptions. Rugs do not block the floor. Door sweep is reserved for furniture; only its open leaf blocks walking.</p><p>Wall TVs have no floor footprint. The full screen-width strip must stay FREE or LOW, with at least one target seating cell. Unknown height fails closed. The current low-object threshold is {rules.H_lowCm} cm.</p><h3>What it does not claim</h3><p>No building or fire regulation check, accessibility certification, optical TV visibility, sunlight analysis, cable routing, real purchasing or 3D model. Rectangular rooms and quarter-turn furniture only. Side-hinge windows use a conservative full-depth envelope; unknown mechanisms remain unverified.</p><h3>Local data</h3><p>Your room is saved in this browser’s local storage under <code>{STORAGE_KEY}</code>. No room data is sent to a backend. Export a JSON copy from the header.</p></section></div>}
  </div>;
}

const subscribeClientMount = () => () => {};
/** Client mount avoids hydrating local persisted data against a different server demo. */
export default function FloortrisApp(props: { store?: FloortrisStore }) {
  const mounted = useSyncExternalStore(subscribeClientMount, () => true, () => false);
  return mounted ? <FloortrisWorkspace {...props} /> : <div className="ft-app ft-loading"><Brand /><p>Opening your room…</p></div>;
}
